#pragma once
namespace ts3d {
    class Types : public QObject {
        Q_OBJECT;
    public:

        enum HPSTypes {
            None = static_cast<unsigned int>(HPS::Type::None),
            GenericMask = static_cast<unsigned int>(HPS::Type::GenericMask),

            World = static_cast<unsigned int>(HPS::Type::World),
            UTF8 = static_cast<unsigned int>(HPS::Type::UTF8),
            EventDispatcher = static_cast<unsigned int>(HPS::Type::EventDispatcher),
            EventHandler = static_cast<unsigned int>(HPS::Type::EventHandler),
            EventNotifier = static_cast<unsigned int>(HPS::Type::EventNotifier),
            UpdateNotifier = static_cast<unsigned int>(HPS::Type::UpdateNotifier),
            SearchResults = static_cast<unsigned int>(HPS::Type::SearchResults),
            FontSearchResults = static_cast<unsigned int>(HPS::Type::FontSearchResults),
            SelectionResults = static_cast<unsigned int>(HPS::Type::SelectionResults),
            SelectionItem = static_cast<unsigned int>(HPS::Type::SelectionItem),
            TreeContext = static_cast<unsigned int>(HPS::Type::TreeContext),
            StreamToolkit = static_cast<unsigned int>(HPS::Type::StreamToolkit),
            DriverEventHandler = static_cast<unsigned int>(HPS::Type::DriverEventHandler),
            HighlightSearchResults = static_cast<unsigned int>(HPS::Type::HighlightSearchResults),

            IONotifier = static_cast<unsigned int>(HPS::Type::IONotifier),
            StreamImportNotifier = static_cast<unsigned int>(HPS::Type::StreamImportNotifier),
            STLImportNotifier = static_cast<unsigned int>(HPS::Type::STLImportNotifier),
            OBJImportNotifier = static_cast<unsigned int>(HPS::Type::OBJImportNotifier),
            ExchangeImportNotifier = static_cast<unsigned int>(HPS::Type::ExchangeImportNotifier),
            SketchupImportNotifier = static_cast<unsigned int>(HPS::Type::SketchupImportNotifier),
            ParasolidImportNotifier = static_cast<unsigned int>(HPS::Type::ParasolidImportNotifier),
            ExchangeTranslationNotifier = static_cast<unsigned int>(HPS::Type::ExchangeTranslationNotifier),
            ExchangeExportNotifier = static_cast<unsigned int>(HPS::Type::ExchangeExportNotifier),
            StreamExportNotifier = static_cast<unsigned int>(HPS::Type::StreamExportNotifier),
            ExchangeReloadNotifier = static_cast<unsigned int>(HPS::Type::ExchangeReloadNotifier),
            DWGImportNotifier = static_cast<unsigned int>(HPS::Type::DWGImportNotifier),
            ExchangeParasolidImportNotifier = static_cast<unsigned int>(HPS::Type::ExchangeParasolidImportNotifier),
            PointCloudImportNotifier = static_cast<unsigned int>(HPS::Type::PointCloudImportNotifier),
            OOCImportNotifier = static_cast<unsigned int>(HPS::Type::OOCImportNotifier),

            SearchResultsIterator = static_cast<unsigned int>(HPS::Type::SearchResultsIterator),
            FontSearchResultsIterator = static_cast<unsigned int>(HPS::Type::FontSearchResultsIterator),
            SelectionResultsIterator = static_cast<unsigned int>(HPS::Type::SelectionResultsIterator),
            HighlightSearchResultsIterator = static_cast<unsigned int>(HPS::Type::HighlightSearchResultsIterator),

            Kit = static_cast<unsigned int>(HPS::Type::Kit),
            MarkerKit = static_cast<unsigned int>(HPS::Type::MarkerKit),
            SphereAttributeKit = static_cast<unsigned int>(HPS::Type::SphereAttributeKit),
            TextAttributeKit = static_cast<unsigned int>(HPS::Type::TextAttributeKit),
            TransparencyKit = static_cast<unsigned int>(HPS::Type::TransparencyKit),
            VisibilityKit = static_cast<unsigned int>(HPS::Type::VisibilityKit),
            VisualEffectsKit = static_cast<unsigned int>(HPS::Type::VisualEffectsKit),
            CuttingSectionAttributeKit = static_cast<unsigned int>(HPS::Type::CuttingSectionAttributeKit),
            CircleKit = static_cast<unsigned int>(HPS::Type::CircleKit),
            CircularArcKit = static_cast<unsigned int>(HPS::Type::CircularArcKit),
            CircularWedgeKit = static_cast<unsigned int>(HPS::Type::CircularWedgeKit),
            CuttingSectionKit = static_cast<unsigned int>(HPS::Type::CuttingSectionKit),
            CylinderKit = static_cast<unsigned int>(HPS::Type::CylinderKit),
            DistantLightKit = static_cast<unsigned int>(HPS::Type::DistantLightKit),
            EllipseKit = static_cast<unsigned int>(HPS::Type::EllipseKit),
            EllipticalArcKit = static_cast<unsigned int>(HPS::Type::EllipticalArcKit),
            InfiniteLineKit = static_cast<unsigned int>(HPS::Type::InfiniteLineKit),
            LineKit = static_cast<unsigned int>(HPS::Type::LineKit),
            NURBSCurveKit = static_cast<unsigned int>(HPS::Type::NURBSCurveKit),
            MeshKit = static_cast<unsigned int>(HPS::Type::MeshKit),
            NURBSSurfaceKit = static_cast<unsigned int>(HPS::Type::NURBSSurfaceKit),
            PolygonKit = static_cast<unsigned int>(HPS::Type::PolygonKit),
            SphereKit = static_cast<unsigned int>(HPS::Type::SphereKit),
            SpotlightKit = static_cast<unsigned int>(HPS::Type::SpotlightKit),
            ShellKit = static_cast<unsigned int>(HPS::Type::ShellKit),
            TextKit = static_cast<unsigned int>(HPS::Type::TextKit),
            MaterialKit = static_cast<unsigned int>(HPS::Type::MaterialKit),
            TrimKit = static_cast<unsigned int>(HPS::Type::TrimKit),
            TextureOptionsKit = static_cast<unsigned int>(HPS::Type::TextureOptionsKit),
            LinePatternKit = static_cast<unsigned int>(HPS::Type::LinePatternKit),
            GlyphKit = static_cast<unsigned int>(HPS::Type::GlyphKit),
            ImageKit = static_cast<unsigned int>(HPS::Type::ImageKit),
            LinePatternOptionsKit = static_cast<unsigned int>(HPS::Type::LinePatternOptionsKit),
            CameraKit = static_cast<unsigned int>(HPS::Type::CameraKit),
            BoundingKit = static_cast<unsigned int>(HPS::Type::BoundingKit),
            CullingKit = static_cast<unsigned int>(HPS::Type::CullingKit),
            CurveAttributeKit = static_cast<unsigned int>(HPS::Type::CurveAttributeKit),
            CylinderAttributeKit = static_cast<unsigned int>(HPS::Type::CylinderAttributeKit),
            EdgeAttributeKit = static_cast<unsigned int>(HPS::Type::EdgeAttributeKit),
            LightingAttributeKit = static_cast<unsigned int>(HPS::Type::LightingAttributeKit),
            LineAttributeKit = static_cast<unsigned int>(HPS::Type::LineAttributeKit),
            MarkerAttributeKit = static_cast<unsigned int>(HPS::Type::MarkerAttributeKit),
            MaterialMappingKit = static_cast<unsigned int>(HPS::Type::MaterialMappingKit),
            NURBSSurfaceAttributeKit = static_cast<unsigned int>(HPS::Type::NURBSSurfaceAttributeKit),
            PostProcessEffectsKit = static_cast<unsigned int>(HPS::Type::PostProcessEffectsKit),
            SelectabilityKit = static_cast<unsigned int>(HPS::Type::SelectabilityKit),
            SelectionOptionsKit = static_cast<unsigned int>(HPS::Type::SelectionOptionsKit),
            StandAloneWindowOptionsKit = static_cast<unsigned int>(HPS::Type::StandAloneWindowOptionsKit),
            OffScreenWindowOptionsKit = static_cast<unsigned int>(HPS::Type::OffScreenWindowOptionsKit),
            ApplicationWindowOptionsKit = static_cast<unsigned int>(HPS::Type::ApplicationWindowOptionsKit),
            HighlightOptionsKit = static_cast<unsigned int>(HPS::Type::HighlightOptionsKit),
            LinePatternParallelKit = static_cast<unsigned int>(HPS::Type::LinePatternParallelKit),
            SubwindowKit = static_cast<unsigned int>(HPS::Type::SubwindowKit),
            PerformanceKit = static_cast<unsigned int>(HPS::Type::PerformanceKit),
            HiddenLineAttributeKit = static_cast<unsigned int>(HPS::Type::HiddenLineAttributeKit),
            DrawingAttributeKit = static_cast<unsigned int>(HPS::Type::DrawingAttributeKit),
            ShaderKit = static_cast<unsigned int>(HPS::Type::ShaderKit),
            DebuggingKit = static_cast<unsigned int>(HPS::Type::DebuggingKit),
            ContourLineKit = static_cast<unsigned int>(HPS::Type::ContourLineKit),
            StreamImportOptionsKit = static_cast<unsigned int>(HPS::Type::StreamImportOptionsKit),
            StreamImportResultsKit = static_cast<unsigned int>(HPS::Type::StreamImportResultsKit),
            StreamExportOptionsKit = static_cast<unsigned int>(HPS::Type::StreamExportOptionsKit),
            StreamExportResultsKit = static_cast<unsigned int>(HPS::Type::StreamExportResultsKit),
            WindowInfoKit = static_cast<unsigned int>(HPS::Type::WindowInfoKit),
            ImageImportOptionsKit = static_cast<unsigned int>(HPS::Type::ImageImportOptionsKit),
            SearchOptionsKit = static_cast<unsigned int>(HPS::Type::SearchOptionsKit),
            ShaderImportOptionsKit = static_cast<unsigned int>(HPS::Type::ShaderImportOptionsKit),
            HardcopyExportOptionsKit = static_cast<unsigned int>(HPS::Type::HardcopyExportOptionsKit),
            AttributeLockKit = static_cast<unsigned int>(HPS::Type::AttributeLockKit),
            TransformMaskKit = static_cast<unsigned int>(HPS::Type::TransformMaskKit),
            ColorInterpolationKit = static_cast<unsigned int>(HPS::Type::ColorInterpolationKit),
            UpdateOptionsKit = static_cast<unsigned int>(HPS::Type::UpdateOptionsKit),
            ImageExportOptionsKit = static_cast<unsigned int>(HPS::Type::ImageExportOptionsKit),
            OBJImportOptionsKit = static_cast<unsigned int>(HPS::Type::OBJImportOptionsKit),
            OBJImportResultsKit = static_cast<unsigned int>(HPS::Type::OBJImportResultsKit),
            STLImportOptionsKit = static_cast<unsigned int>(HPS::Type::STLImportOptionsKit),
            STLImportResultsKit = static_cast<unsigned int>(HPS::Type::STLImportResultsKit),
            ShellOptimizationOptionsKit = static_cast<unsigned int>(HPS::Type::ShellOptimizationOptionsKit),
            ShellRelationOptionsKit = static_cast<unsigned int>(HPS::Type::ShellRelationOptionsKit),
            ShellRelationResultsKit = static_cast<unsigned int>(HPS::Type::ShellRelationResultsKit),
            GridKit = static_cast<unsigned int>(HPS::Type::GridKit),
            CutGeometryGatheringOptionsKit = static_cast<unsigned int>(HPS::Type::CutGeometryGatheringOptionsKit),
            SegmentOptimizationOptionsKit = static_cast<unsigned int>(HPS::Type::SegmentOptimizationOptionsKit),
            PointCloudImportOptionsKit = static_cast<unsigned int>(HPS::Type::PointCloudImportOptionsKit),
            PointCloudImportResultsKit = static_cast<unsigned int>(HPS::Type::PointCloudImportResultsKit),
            ShapeKit = static_cast<unsigned int>(HPS::Type::ShapeKit),
            HardcopyGDIExportOptionsKit = static_cast<unsigned int>(HPS::Type::HardcopyGDIExportOptionsKit),
            HighlightSearchOptionsKit = static_cast<unsigned int>(HPS::Type::HighlightSearchOptionsKit),

            LinePatternElement = static_cast<unsigned int>(HPS::Type::LinePatternElement),
            SolidLinePatternElement = static_cast<unsigned int>(HPS::Type::SolidLinePatternElement),
            BlankLinePatternElement = static_cast<unsigned int>(HPS::Type::BlankLinePatternElement),
            GlyphLinePatternElement = static_cast<unsigned int>(HPS::Type::GlyphLinePatternElement),

            GlyphElement = static_cast<unsigned int>(HPS::Type::GlyphElement),
            DotGlyphElement = static_cast<unsigned int>(HPS::Type::DotGlyphElement),
            LineGlyphElement = static_cast<unsigned int>(HPS::Type::LineGlyphElement),
            EllipseGlyphElement = static_cast<unsigned int>(HPS::Type::EllipseGlyphElement),
            CircularArcGlyphElement = static_cast<unsigned int>(HPS::Type::CircularArcGlyphElement),
            InfiniteLineGlyphElement = static_cast<unsigned int>(HPS::Type::InfiniteLineGlyphElement),
            SphereGlyphElement = static_cast<unsigned int>(HPS::Type::SphereGlyphElement),

            TrimElement = static_cast<unsigned int>(HPS::Type::TrimElement),

            ConditionalExpression = static_cast<unsigned int>(HPS::Type::ConditionalExpression),
            NOTCondition = static_cast<unsigned int>(HPS::Type::NOTCondition),
            ANDCondition = static_cast<unsigned int>(HPS::Type::ANDCondition),
            ORCondition = static_cast<unsigned int>(HPS::Type::ORCondition),
            XORCondition = static_cast<unsigned int>(HPS::Type::XORCondition),
            EQCondition = static_cast<unsigned int>(HPS::Type::EQCondition),
            NEQCondition = static_cast<unsigned int>(HPS::Type::NEQCondition),
            GTCondition = static_cast<unsigned int>(HPS::Type::GTCondition),
            LTCondition = static_cast<unsigned int>(HPS::Type::LTCondition),
            GTEQCondition = static_cast<unsigned int>(HPS::Type::GTEQCondition),
            LTEQCondition = static_cast<unsigned int>(HPS::Type::LTEQCondition),

            ShapeElement = static_cast<unsigned int>(HPS::Type::ShapeElement),
            PolygonShapeElement = static_cast<unsigned int>(HPS::Type::PolygonShapeElement),
            EllipseShapeElement = static_cast<unsigned int>(HPS::Type::EllipseShapeElement),
            CircleShapeElement = static_cast<unsigned int>(HPS::Type::CircleShapeElement),
            EllipticalArcShapeElement = static_cast<unsigned int>(HPS::Type::EllipticalArcShapeElement),
            AnchorShapeElement = static_cast<unsigned int>(HPS::Type::AnchorShapeElement),
            LineShapeElement = static_cast<unsigned int>(HPS::Type::LineShapeElement),
            CircularArcShapeElement = static_cast<unsigned int>(HPS::Type::CircularArcShapeElement),
            LeaderLineClippingElement = static_cast<unsigned int>(HPS::Type::LeaderLineClippingElement),

            MouseState = static_cast<unsigned int>(HPS::Type::MouseState),
            TouchState = static_cast<unsigned int>(HPS::Type::TouchState),
            KeyboardState = static_cast<unsigned int>(HPS::Type::KeyboardState),
            FontInfoState = static_cast<unsigned int>(HPS::Type::FontInfoState),
            HighlightState = static_cast<unsigned int>(HPS::Type::HighlightState),

            KeyPath = static_cast<unsigned int>(HPS::Type::KeyPath),

            Key = static_cast<unsigned int>(HPS::Type::Key),
            IncludeKey = static_cast<unsigned int>(HPS::Type::IncludeKey),
            PortfolioKey = static_cast<unsigned int>(HPS::Type::PortfolioKey),
            StyleKey = static_cast<unsigned int>(HPS::Type::StyleKey),

            SegmentKey = static_cast<unsigned int>(HPS::Type::SegmentKey),
            WindowKey = static_cast<unsigned int>(HPS::Type::WindowKey),
            StandAloneWindowKey = static_cast<unsigned int>(HPS::Type::StandAloneWindowKey),
            OffScreenWindowKey = static_cast<unsigned int>(HPS::Type::OffScreenWindowKey),
            ApplicationWindowKey = static_cast<unsigned int>(HPS::Type::ApplicationWindowKey),

            GeometryKey = static_cast<unsigned int>(HPS::Type::GeometryKey),
            ReferenceKey = static_cast<unsigned int>(HPS::Type::ReferenceKey),
            CircleKey = static_cast<unsigned int>(HPS::Type::CircleKey),
            CircularArcKey = static_cast<unsigned int>(HPS::Type::CircularArcKey),
            CircularWedgeKey = static_cast<unsigned int>(HPS::Type::CircularWedgeKey),
            CuttingSectionKey = static_cast<unsigned int>(HPS::Type::CuttingSectionKey),
            CylinderKey = static_cast<unsigned int>(HPS::Type::CylinderKey),
            EllipseKey = static_cast<unsigned int>(HPS::Type::EllipseKey),
            EllipticalArcKey = static_cast<unsigned int>(HPS::Type::EllipticalArcKey),
            InfiniteLineKey = static_cast<unsigned int>(HPS::Type::InfiniteLineKey),
            LineKey = static_cast<unsigned int>(HPS::Type::LineKey),
            DistantLightKey = static_cast<unsigned int>(HPS::Type::DistantLightKey),
            SpotlightKey = static_cast<unsigned int>(HPS::Type::SpotlightKey),
            MarkerKey = static_cast<unsigned int>(HPS::Type::MarkerKey),
            MeshKey = static_cast<unsigned int>(HPS::Type::MeshKey),
            NURBSCurveKey = static_cast<unsigned int>(HPS::Type::NURBSCurveKey),
            NURBSSurfaceKey = static_cast<unsigned int>(HPS::Type::NURBSSurfaceKey),
            PolygonKey = static_cast<unsigned int>(HPS::Type::PolygonKey),
            ShellKey = static_cast<unsigned int>(HPS::Type::ShellKey),
            SphereKey = static_cast<unsigned int>(HPS::Type::SphereKey),
            TextKey = static_cast<unsigned int>(HPS::Type::TextKey),
            GridKey = static_cast<unsigned int>(HPS::Type::GridKey),

            Definition = static_cast<unsigned int>(HPS::Type::Definition),
            NamedStyleDefinition = static_cast<unsigned int>(HPS::Type::NamedStyleDefinition),
            TextureDefinition = static_cast<unsigned int>(HPS::Type::TextureDefinition),
            LinePatternDefinition = static_cast<unsigned int>(HPS::Type::LinePatternDefinition),
            GlyphDefinition = static_cast<unsigned int>(HPS::Type::GlyphDefinition),
            CubeMapDefinition = static_cast<unsigned int>(HPS::Type::CubeMapDefinition),
            ImageDefinition = static_cast<unsigned int>(HPS::Type::ImageDefinition),
            MaterialPaletteDefinition = static_cast<unsigned int>(HPS::Type::MaterialPaletteDefinition),
            ShaderDefinition = static_cast<unsigned int>(HPS::Type::ShaderDefinition),
            ShapeDefinition = static_cast<unsigned int>(HPS::Type::ShapeDefinition),

            Control = static_cast<unsigned int>(HPS::Type::Control),
            CameraControl = static_cast<unsigned int>(HPS::Type::CameraControl),
            SelectabilityControl = static_cast<unsigned int>(HPS::Type::SelectabilityControl),
            MarkerAttributeControl = static_cast<unsigned int>(HPS::Type::MarkerAttributeControl),
            SphereAttributeControl = static_cast<unsigned int>(HPS::Type::SphereAttributeControl),
            LightingAttributeControl = static_cast<unsigned int>(HPS::Type::LightingAttributeControl),
            CylinderAttributeControl = static_cast<unsigned int>(HPS::Type::CylinderAttributeControl),
            TextAttributeControl = static_cast<unsigned int>(HPS::Type::TextAttributeControl),
            LineAttributeControl = static_cast<unsigned int>(HPS::Type::LineAttributeControl),
            EdgeAttributeControl = static_cast<unsigned int>(HPS::Type::EdgeAttributeControl),
            CurveAttributeControl = static_cast<unsigned int>(HPS::Type::CurveAttributeControl),
            ModellingMatrixControl = static_cast<unsigned int>(HPS::Type::ModellingMatrixControl),
            TextureMatrixControl = static_cast<unsigned int>(HPS::Type::TextureMatrixControl),
            CullingControl = static_cast<unsigned int>(HPS::Type::CullingControl),
            TransparencyControl = static_cast<unsigned int>(HPS::Type::TransparencyControl),
            MaterialMappingControl = static_cast<unsigned int>(HPS::Type::MaterialMappingControl),
            NURBSSurfaceAttributeControl = static_cast<unsigned int>(HPS::Type::NURBSSurfaceAttributeControl),
            PostProcessEffectsControl = static_cast<unsigned int>(HPS::Type::PostProcessEffectsControl),
            BoundingControl = static_cast<unsigned int>(HPS::Type::BoundingControl),
            VisualEffectsControl = static_cast<unsigned int>(HPS::Type::VisualEffectsControl),
            SelectionOptionsControl = static_cast<unsigned int>(HPS::Type::SelectionOptionsControl),
            HighlightOptionsControl = static_cast<unsigned int>(HPS::Type::HighlightOptionsControl),
            DefinitionControl = static_cast<unsigned int>(HPS::Type::DefinitionControl),
            SelectionControl = static_cast<unsigned int>(HPS::Type::SelectionControl),
            HighlightControl = static_cast<unsigned int>(HPS::Type::HighlightControl),
            StandAloneWindowOptionsControl = static_cast<unsigned int>(HPS::Type::StandAloneWindowOptionsControl),
            OffScreenWindowOptionsControl = static_cast<unsigned int>(HPS::Type::OffScreenWindowOptionsControl),
            ApplicationWindowOptionsControl = static_cast<unsigned int>(HPS::Type::ApplicationWindowOptionsControl),
            VisibilityControl = static_cast<unsigned int>(HPS::Type::VisibilityControl),
            SubwindowControl = static_cast<unsigned int>(HPS::Type::SubwindowControl),
            PerformanceControl = static_cast<unsigned int>(HPS::Type::PerformanceControl),
            HiddenLineAttributeControl = static_cast<unsigned int>(HPS::Type::HiddenLineAttributeControl),
            DrawingAttributeControl = static_cast<unsigned int>(HPS::Type::DrawingAttributeControl),
            DebuggingControl = static_cast<unsigned int>(HPS::Type::DebuggingControl),
            ContourLineControl = static_cast<unsigned int>(HPS::Type::ContourLineControl),
            StyleControl = static_cast<unsigned int>(HPS::Type::StyleControl),
            ConditionControl = static_cast<unsigned int>(HPS::Type::ConditionControl),
            PortfolioControl = static_cast<unsigned int>(HPS::Type::PortfolioControl),
            WindowInfoControl = static_cast<unsigned int>(HPS::Type::WindowInfoControl),
            AttributeLockControl = static_cast<unsigned int>(HPS::Type::AttributeLockControl),
            TransformMaskControl = static_cast<unsigned int>(HPS::Type::TransformMaskControl),
            ColorInterpolationControl = static_cast<unsigned int>(HPS::Type::ColorInterpolationControl),
            UpdateOptionsControl = static_cast<unsigned int>(HPS::Type::UpdateOptionsControl),
            CuttingSectionAttributeControl = static_cast<unsigned int>(HPS::Type::CuttingSectionAttributeControl),

            LibraryMask = static_cast<unsigned int>(HPS::Type::LibraryMask),

            Sprocket = static_cast<unsigned int>(HPS::Type::Sprocket),
            Canvas = static_cast<unsigned int>(HPS::Type::Canvas),
            Layout = static_cast<unsigned int>(HPS::Type::Layout),
            View = static_cast<unsigned int>(HPS::Type::View),
            Model = static_cast<unsigned int>(HPS::Type::Model),
            Operator = static_cast<unsigned int>(HPS::Type::Operator),
            SprocketPath = static_cast<unsigned int>(HPS::Type::SprocketPath),

            SprocketControl = static_cast<unsigned int>(HPS::Type::SprocketControl),
            OperatorControl = static_cast<unsigned int>(HPS::Type::OperatorControl),
            NavigationCubeControl = static_cast<unsigned int>(HPS::Type::NavigationCubeControl),
            AxisTriadControl = static_cast<unsigned int>(HPS::Type::AxisTriadControl),

            SprocketKit = static_cast<unsigned int>(HPS::Type::SprocketKit),

            Metadata = static_cast<unsigned int>(HPS::Type::Metadata),
            IntegerMetadata = static_cast<unsigned int>(HPS::Type::IntegerMetadata),
            UnsignedIntegerMetadata = static_cast<unsigned int>(HPS::Type::UnsignedIntegerMetadata),
            DoubleMetadata = static_cast<unsigned int>(HPS::Type::DoubleMetadata),
            StringMetadata = static_cast<unsigned int>(HPS::Type::StringMetadata),
            TimeMetadata = static_cast<unsigned int>(HPS::Type::TimeMetadata),
            BooleanMetadata = static_cast<unsigned int>(HPS::Type::BooleanMetadata),

            Component = static_cast<unsigned int>(HPS::Type::Component),
            Filter = static_cast<unsigned int>(HPS::Type::Filter),
            Capture = static_cast<unsigned int>(HPS::Type::Capture),
            CADModel = static_cast<unsigned int>(HPS::Type::CADModel),
            ComponentPath = static_cast<unsigned int>(HPS::Type::ComponentPath),

            ExchangeMask = static_cast<unsigned int>(HPS::Type::ExchangeMask),
            ExchangeComponent = static_cast<unsigned int>(HPS::Type::ExchangeComponent),
            ExchangeSheet = static_cast<unsigned int>(HPS::Type::ExchangeSheet),
            ExchangeProductOccurrence = static_cast<unsigned int>(HPS::Type::ExchangeProductOccurrence),
            ExchangeFilter = static_cast<unsigned int>(HPS::Type::ExchangeFilter),
            ExchangeCapture = static_cast<unsigned int>(HPS::Type::ExchangeCapture),
            ExchangeCADModel = static_cast<unsigned int>(HPS::Type::ExchangeCADModel),
            ExchangeConfiguration = static_cast<unsigned int>(HPS::Type::ExchangeConfiguration),
            ExchangeImportOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeImportOptionsKit),
            ExchangeExportACISOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExportACISOptionsKit),
            ExchangeExportIGESOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExportIGESOptionsKit),
            ExchangeExportJTOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExportJTOptionsKit),
            ExchangeExportParasolidOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExportParasolidOptionsKit),
            ExchangeExportPRCOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExportPRCOptionsKit),
            ExchangeExportSTEPOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExportSTEPOptionsKit),
            ExchangeExportSTLOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExportSTLOptionsKit),
            ExchangeExportU3DOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExportU3DOptionsKit),
            ExchangeExportXMLOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExportXMLOptionsKit),
            ExchangeTessellationOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeTessellationOptionsKit),
            ExchangeModelFileImportOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeModelFileImportOptionsKit),
            ExchangeTranslationOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeTranslationOptionsKit),
            ExchangeNURBSConversionOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeNURBSConversionOptionsKit),
            ExchangeExport3MFOptionsKit = static_cast<unsigned int>(HPS::Type::ExchangeExport3MFOptionsKit),

            PublishMask = static_cast<unsigned int>(HPS::Type::PublishMask),
            PublishDocumentKit = static_cast<unsigned int>(HPS::Type::PublishDocumentKit),
            PublishPageKit = static_cast<unsigned int>(HPS::Type::PublishPageKit),
            PublishTemplateKit = static_cast<unsigned int>(HPS::Type::PublishTemplateKit),
            PublishAnnotationKit = static_cast<unsigned int>(HPS::Type::PublishAnnotationKit),
            PublishArtworkKit = static_cast<unsigned int>(HPS::Type::PublishArtworkKit),
            PublishViewKit = static_cast<unsigned int>(HPS::Type::PublishViewKit),
            PublishTextKit = static_cast<unsigned int>(HPS::Type::PublishTextKit),
            PublishImageKit = static_cast<unsigned int>(HPS::Type::PublishImageKit),
            PublishTableKit = static_cast<unsigned int>(HPS::Type::PublishTableKit),
            PublishExportOptionsKit = static_cast<unsigned int>(HPS::Type::PublishExportOptionsKit),
            PublishLinkKit = static_cast<unsigned int>(HPS::Type::PublishLinkKit),
            PublishButtonKit = static_cast<unsigned int>(HPS::Type::PublishButtonKit),
            PublishTextFieldKit = static_cast<unsigned int>(HPS::Type::PublishTextFieldKit),
            PublishSlideTableKit = static_cast<unsigned int>(HPS::Type::PublishSlideTableKit),
            PublishCheckBoxKit = static_cast<unsigned int>(HPS::Type::PublishCheckBoxKit),
            PublishRadioButtonKit = static_cast<unsigned int>(HPS::Type::PublishRadioButtonKit),
            PublishListBoxKit = static_cast<unsigned int>(HPS::Type::PublishListBoxKit),
            PublishDropDownListKit = static_cast<unsigned int>(HPS::Type::PublishDropDownListKit),
            PublishSignatureFieldKit = static_cast<unsigned int>(HPS::Type::PublishSignatureFieldKit),

            PublishDocumentKey = static_cast<unsigned int>(HPS::Type::PublishDocumentKey),
            PublishPageControl = static_cast<unsigned int>(HPS::Type::PublishPageControl),

            ExchangeParasolidMask = static_cast<unsigned int>(HPS::Type::ExchangeParasolidMask),

            SceneTree = static_cast<unsigned int>(HPS::Type::SceneTree),
            SceneTreeItem = static_cast<unsigned int>(HPS::Type::SceneTreeItem),

            ComponentTree = static_cast<unsigned int>(HPS::Type::ComponentTree),
            ComponentTreeItem = static_cast<unsigned int>(HPS::Type::ComponentTreeItem),

            SketchupMask = static_cast<unsigned int>(HPS::Type::SketchupMask),
            SketchupImportOptionsKit = static_cast<unsigned int>(HPS::Type::SketchupImportOptionsKit),
            SketchupImportResultsKit = static_cast<unsigned int>(HPS::Type::SketchupImportResultsKit),

            ParasolidMask = static_cast<unsigned int>(HPS::Type::ParasolidMask),
            ParasolidComponent = static_cast<unsigned int>(HPS::Type::ParasolidComponent),
            ParasolidCADModel = static_cast<unsigned int>(HPS::Type::ParasolidCADModel),
            ParasolidImportOptionsKit = static_cast<unsigned int>(HPS::Type::ParasolidImportOptionsKit),
            ParasolidFacetTessellationKit = static_cast<unsigned int>(HPS::Type::ParasolidFacetTessellationKit),
            ParasolidLineTessellationKit = static_cast<unsigned int>(HPS::Type::ParasolidLineTessellationKit),
            ParasolidExportOptionsKit = static_cast<unsigned int>(HPS::Type::ParasolidExportOptionsKit),

            DWGMask = static_cast<unsigned int>(HPS::Type::DWGMask),
            DWGComponent = static_cast<unsigned int>(HPS::Type::DWGComponent),
            DWGLayer = static_cast<unsigned int>(HPS::Type::DWGLayer),
            DWGLayout = static_cast<unsigned int>(HPS::Type::DWGLayout),
            DWGCADModel = static_cast<unsigned int>(HPS::Type::DWGCADModel),
            DWGImportOptionsKit = static_cast<unsigned int>(HPS::Type::DWGImportOptionsKit),

            OOCMask = static_cast<unsigned int>(HPS::Type::OOCMask),
            OOCImportOptionsKit = static_cast<unsigned int>(HPS::Type::OOCImportOptionsKit),
            OOCImportResultsKit = static_cast<unsigned int>(HPS::Type::OOCImportResultsKit),

            HTMLMask = static_cast<unsigned int>(HPS::Type::HTMLMask),


            IONotifierData = static_cast<unsigned int>(HPS::Type::IONotifierData),
            StreamImportNotifierData = static_cast<unsigned int>(HPS::Type::StreamImportNotifierData),
            STLImportNotifierData = static_cast<unsigned int>(HPS::Type::STLImportNotifierData),
            OBJImportNotifierData = static_cast<unsigned int>(HPS::Type::OBJImportNotifierData),
            ExchangeImportNotifierData = static_cast<unsigned int>(HPS::Type::ExchangeImportNotifierData),
            SketchupImportNotifierData = static_cast<unsigned int>(HPS::Type::SketchupImportNotifierData),
            ParasolidImportNotifierData = static_cast<unsigned int>(HPS::Type::ParasolidImportNotifierData),
            ExchangeTranslationNotifierData = static_cast<unsigned int>(HPS::Type::ExchangeTranslationNotifierData),
            ExchangeExportNotifierData = static_cast<unsigned int>(HPS::Type::ExchangeExportNotifierData),
            StreamExportNotifierData = static_cast<unsigned int>(HPS::Type::StreamExportNotifierData),
            DWGImportNotifierData = static_cast<unsigned int>(HPS::Type::DWGImportNotifierData),
            ExchangeParasolidImportNotifierData = static_cast<unsigned int>(HPS::Type::ExchangeParasolidImportNotifierData),
            PointCloudImportNotifierData = static_cast<unsigned int>(HPS::Type::PointCloudImportNotifierData),
            OOCImportNotifierData = static_cast<unsigned int>(HPS::Type::OOCImportNotifierData),
        };
        Q_ENUM( HPSTypes );
    public:

        static QString toString( HPS::Type const &type );
    };
}